### ISSUE TITLE
No results for PR #8899

### ISSUE THREAD

**Issue by foolip** [w3c/wptdash#56]
https://github.com/w3c/web-platform-tests/pull/8899 links to https://pulls.web-platform-tests.org/build/22362 but there are no results there at all.

Quite likely related to https://github.com/w3c/wpt-pullresults/issues/47

**Comment by foolip** [comment]
@mattl, are you subscribed to all new issues in this repo, or should I ping you like this?

**Comment by boazsender** [comment]
@lukebjerring re-ran these manually and results (albiet failing ones) are now populating.

I thought this may have been because of the changes I made and deployed yesterday, which caused some web server on pulls.web-platform-tests.org, but it appears that other PRs from before and after that have gotten results. This must have been caused by another issue, which we should investigate in #47.
